### ISSUE TITLE
Unable operate tools

### ISSUE THREAD

**Issue by genglinyang** [chjch/lucis_qgis#1]
1. reclassify field
![image](https://user-images.githubusercontent.com/77020104/103682804-59aa1580-4f57-11eb-8788-1b58eb35a629.png)
![image](https://user-images.githubusercontent.com/77020104/103682778-5020ad80-4f57-11eb-978c-854ef49540f1.png)

2. spatial join
![image](https://user-images.githubusercontent.com/77020104/103682829-63337d80-4f57-11eb-8122-0e5447474e97.png)
![image](https://user-images.githubusercontent.com/77020104/103682840-662e6e00-4f57-11eb-8f5c-acda14a6aa17.png)

3. select by location
![image](https://user-images.githubusercontent.com/77020104/103682879-73e3f380-4f57-11eb-88fb-42832af44fb9.png)

**Comment by chjch** [comment]
The issue has been moved to  #3 #4 #6
