### ISSUE TITLE
Reclassify-Solution Needed for the Mandatory Ascending Value Input in the "Old Values"

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#10]
Need a solution to relieve the mandatory ascending value input in the "Old Values".

![image](https://user-images.githubusercontent.com/77020250/105928385-df2f5b80-6013-11eb-9761-e45524f664a3.png)

**Comment by chjch** [comment]
Tool upgraded. Please upgrade pylusat to solve this issue.
