### ISSUE TITLE
Spatial Join - Can not join the layer that has the common column name with the target layer

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#11]
![image](https://user-images.githubusercontent.com/77020250/111414293-176b2600-86b6-11eb-904b-0b734f182d3b.png)

Can not join the layer that has the common column name with the target layer.

The problem is that the repeated column name is added by "2" as the suffix.

**Comment by chjch** [comment]
Problem solved. Please upgrade pylusat.
