### ISSUE TITLE
Zonal Statistics - Abbreviation of the algorithm name needed

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#12]
When running the Zonal Statistics tool, the name of the algorithm will be added as a suffix to the new column. However, the algorithm name like "median", "mean", "count", "majority", "minority", "range", and "unique" should have an abbreviation in order to free up the character bit in the column name.

**Comment by chjch** [comment]
Problem solved by using the "geopackage" engine when saving the GeoDataFrame to a layer in QGIS. Please upgrade the script.
