### ISSUE TITLE
Spatial join - Value Error: not enough value to unpack

### ISSUE THREAD

**Issue by genglinyang** [chjch/lucis_qgis#3]
**Spatial Join**
![image](https://user-images.githubusercontent.com/77020104/103684186-2a94a380-4f59-11eb-9409-96936dd0250b.png)
![image](https://user-images.githubusercontent.com/77020104/103684193-2d8f9400-4f59-11eb-8092-0c0b904169f3.png)

**Comment by chjch** [comment]
Problem solved by fixing bugs. Issue closed.
