### ISSUE TITLE
Select by location - Attribute Error: can't delete attribute

### ISSUE THREAD

**Issue by genglinyang** [chjch/lucis_qgis#4]
Select by location
![image](https://user-images.githubusercontent.com/77020104/103684390-7ba49780-4f59-11eb-8651-cc8fbc564dd9.png)
![image](https://user-images.githubusercontent.com/77020104/103684405-82330f00-4f59-11eb-9e84-51e35b08d50f.png)

**Comment by chjch** [comment]
Fixed the problem. The tool now only outputs selected features that met the specified spatial relationship. Please update pylusat. Issue closed.
