### ISSUE TITLE
Distance to Line Features - Can't save as a temporary file in Distance to Line Features tool

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#5]
There is no output layer when we output a file as temporary in the tool **Distance to Line Features**. We must save it as a new layer and name it, otherwise, there would be no output layer.

**Comment by slyu1** [comment]
There is no temporary output layer when we save the output file as temporary in the **Distance to Line Features** tool. We have to save it as a permanent file and name it, otherwise, we can't get the output file.

**Comment by chjch** [comment]
Problem solved by changing the output type from _QgsProcessingParameterFileDestination_ to _QgsProcessingParameterVectorDestination_. Issue closed.
