### ISSUE TITLE
Reclassify -the Reclassify tool doesn't work

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#6]
When we use the **Reclassify** tool to handle the sample attribute **pointid** (including integer values ranging from 1 to  781) in a shapefile, we can't get the right output when we set the parameters as shown in the following figure.
![image](https://user-images.githubusercontent.com/77020250/103685476-4b5df880-4f5b-11eb-8e67-d2a8519430f6.png)

The error is shown by the following figure.
![image](https://user-images.githubusercontent.com/77020250/103685311-02a63f80-4f5b-11eb-8689-554bdc01344d.png)

**Comment by chjch** [comment]
Problem solved by fixing the pylusat package. Please upgrade your pylusat. Also, after the upgrading, please update your reclassify.py file with git since the tool itself has also been updated.

**Comment by slyu1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Got it. Thanks!Best,Shenyu Lyu
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                s.lyu
                            
                    
                        
                            
                                    s.lyu@ufl.edu
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/15/2021 15:15，Changjie Chen<notifications@github.com> wrote： 



[External Email]





Problem solved by fixing the pylusat package. Please upgrade your pylusat. Also, after the upgrading, please update your reclassify.py file with git since the tool itself has also been updated.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
