### ISSUE TITLE
Zonal Statistics- "Level 0" Problem

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#8]
Encounter the "Level 0“ problem when running Zonal Statistics the third time.

![image](https://user-images.githubusercontent.com/77020250/105911832-99b16500-5ff8-11eb-8249-f51e96d9deef.png)

**Comment by chjch** [comment]
Problem solved by updating pylusat function zonal_stats_raster. Please upgrade pylusat.
