### ISSUE TITLE
Reclassify-Allowable Multiple Same Values for the "Old Values" Entry

### ISSUE THREAD

**Issue by slyu1** [chjch/lucis_qgis#9]
In the Reclassify tool, multiple same values should be allowed for the "Old Values" entry.

![image](https://user-images.githubusercontent.com/77020250/105926881-db4e0a00-6010-11eb-9a80-6c316e7e0e4f.png)

**Comment by chjch** [comment]
The tool now supports random ordering of intervals. Please upgrade pylusat.
